Hospital/urls.py
from django.contrib import admin
from django.urls import path
from Management.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dummy,name='dummy'),
    path('index/',index,name='index'),
    path('Login/',Login,name='Login'),
    path('Logout/',Logout,name='Logout'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('view_doctor/',view_doctor,name='view_doctor'),
    path('add_doctor/',add_doctor,name='add_doctor'),
    path('delete_doctor(?p<int:pid>)',delete_doctor,name='delete_doctor'),
    path('view_patient/',view_patient,name='view_patient'),
    path('add_patient/',add_patient,name='add_patient'),
    path('delete_patient(?p<int:pid>)',delete_patient,name='delete_patient'),
    path('add_appointment/',add_appointment,name='add_appointment'),
    path('delete_appointment(?p<int:pid>)',delete_appointment,name='delete_appointment'),
    path('view_appointment/',view_appointment,name='view_appointment'),
    path('discharge/(?p<int:id>)',discharge,name='discharge'),
    path('not_discharge/(?p<int:id>)',not_discharge,name='not_discharge'),
    path('patientdetail/(?p<int:id>)',patientdetails,name='patientdetails'),

]

Management/models.py
from django.db import models

# Create your models here.

class Doctor(models.Model):
    name=models.CharField(max_length=100)
    gender=models.CharField(max_length=10)
    mobile=models.IntegerField()
    specialization=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Patient(models.Model):
    lis=[('Male','male'),('Female','female')]
    pname=models.CharField(max_length=100)
    gender=models.CharField(max_length=6,choices=lis)
    pmobile=models.IntegerField()
    address=models.CharField(max_length=150)
    fees=models.IntegerField(default=0)
    paid=models.IntegerField(default=0)
    balance=models.IntegerField(default=0)
    pay=models.IntegerField(default=0)
    discharge=models.BooleanField(default=False)

    def __str__(self):
        return self.pname

class Appointment(models.Model):
    doctor=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    patient=models.ForeignKey(Patient,on_delete=models.CASCADE)
    date=models.DateField(null=True)
    time=models.TimeField(null=True)

    def __str__(self):
        return self.doctor.name+'--'+ self.patient.pname

Management/forms.py
from django import forms

from Management.models import *

class DoctorForm(forms.ModelForm):
    class Meta:
        model=Doctor
        fields='__all__'
    

class PatientrForm(forms.ModelForm):
    lis=[('Male','male'),('Female','female')]
    gender=forms.ChoiceField(widget=forms.RadioSelect,choices=lis)
    class Meta:
        model=Patient
        lis=[('Male','male'),('Female','female')]
        gender=forms.ChoiceField(widget=forms.RadioSelect(choices=lis))
        fields=['pname','gender','pmobile','address','fees','paid','balance','pay','discharge']

    

class AppointmentForm(forms.ModelForm):
    class Meta:
        model=Appointment
        fields='__all__'

Management/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout,login
from Management.models import *
from django.contrib import messages
from .forms import *
# Create your views here.




def dummy(request):
    if not request.user.is_staff:
        return redirect('Login')
    return render(request,'dummy.html')

def index(request):
    if not request.user.is_staff:
        return redirect('Login')
    doctors=Doctor.objects.all()
    patients=Patient.objects.all()
    appointments=Appointment.objects.all()

    d=0
    p=0
    a=0
    for i in doctors:
        d+=1
    for i in patients:
        p+=1
    for i in appointments:
        a+=1
    d1={'d':d,'p':p,'a':a}
    return render(request,'index.html',d1)

def Login(request):
    error=''
    if request.method=='POST':
        u=request.POST['an']
        p=request.POST['pw']
        user=authenticate(username=u,password=p)

        try:
            if  user.is_staff:
                login(request,user)
                error='no'
            else:
                error='yes'

        except:
             error='yes'
    d={'error':error}
    return render(request,'Login.html',d)

def Logout(request):
    if not request.user.is_staff:
        return redirect('Login')
    logout(request)
    return redirect('Login')


def contact(request):
    return render(request,'contact.html')

def about(request):
    return render(request,'about.html')

def view_doctor(request):
    if not request.user.is_staff:
        return redirect('Login')
    doc=Doctor.objects.all()
    d={"doc":doc}
    return render(request,'view_doctor.html',d)

def add_doctor(request):
    error=''
    if request.method=='POST':
        n=request.POST['an']
        c=request.POST['co']
        g=request.POST['g']
        s=request.POST['sc']

        if any(char.isdigit() for char in n ):
            error=messages.error(request,('Name contains string'))
        else:
            try:
                doc=Doctor.objects.create(name=n,mobile=c,gender=g,specialization=s)
                error='no'
            except Exception as e:
                error='yes'
    d={'error':error}
    return render(request,'add_doctor.html',d)

def delete_doctor(request,pid):
    if not request.user.is_staff:
        return redirect('Login')
    
    doc=Doctor.objects.get(id=pid)
    doc.delete()
    return redirect('view_doctor')

def view_patient(request):
    if not request.user.is_staff:
        return redirect('Login')
    pat=Patient.objects.all()
    d={"pat":pat}
    return render(request,'view_patient.html',d)

def add_patient(request):
    error=''
    pfo=PatientrForm()
    if request.method=='POST':
        pname=request.POST.get('pname')
        
        if any(char.isdigit() for char in pname ):
            error=messages.error(request,('Name contains string')) 
        else:
            try:
                mpfo=PatientrForm(request.POST)
                if mpfo.is_valid():
                    mpfo.save()
                    error='no'
            except Exception as e:
                error='yes'
    d={'error':error,'pfo':pfo,}
    return render(request,'add_patient.html',d)

def delete_patient(request,pid):
    if not request.user.is_staff:
        return redirect('Login')

    pat=Patient.objects.get(id=pid)
    pat.delete()
    return redirect('view_patient')


def view_appointment(request):
    if not request.user.is_staff:
        return redirect('Login')
    appo=Appointment.objects.all()
    d={"appo":appo}
    return render(request,'view_appointment.html',d)


def add_appointment(request):
    error=''
    do=Doctor.objects.all()
    pa=Patient.objects.all()
    if request.method=='POST':
        d=request.POST['doctor']
        p=request.POST['patient']
        d1=request.POST['date']
        t=request.POST['time']

        doc1=Doctor.objects.filter(name=d).first()
        pa1=Patient.objects.filter(pname=p).first()
        try:
            doc=Appointment.objects.create(doctor=doc1,patient=pa1,date=d1,time=t)
            error='no'
        except:
            error='yes'
    d={'error':error,'do':do,'pa':pa}
    return render(request,'add_appointment.html',d)

def delete_appointment(request,pid):
    if not request.user.is_staff:
        return redirect('Login')

    appo=Appointment.objects.get(id=pid)
    appo.delete()
    return redirect('view_appointment')


def discharge(request,id):
    pat=Patient.objects.get(pk=id)
    if pat.balance==0:
        pat.discharge=True
        pat.save()
    else:
        messages.error(request,("Fees Pending"))
    return redirect('view_patient')

def not_discharge(request,id):
    pat=Patient.objects.get(pk=id)
    pat.discharge=False
    pat.save()
    return redirect('view_patient')

def patientdetails(request,id):
    pat=Patient.objects.get(pk=id)
    
    if request.method=='POST':

        pay=int(request.POST['pay'])
        pat.pay=pay
        pat.paid+=pay
        pat.balance=pat.fees - pat.paid
        pat.save()
        return redirect('view_patient')
    d={'pat':pat}
    
    return render(request,'patient_detail.html',d)

templates/Login.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>login page</title>
{% endblock %}


{% block body %}
    {% load static %}
    
        {% if error == "no" %}
            <script>
                alert('Logged In Successfully');
                window.location=('{% url "index" %}');
                
            </script>
        {% elif error == "yes" %}

        
            <script>
                alert('Invalid Login,Try Again');
               
                
            </script>
        {% endif %}



    <div class="container" style="margin-top: 50px">
        <h2 class="text-center">Admin Login</h2>
        <div style="display:flex; flex-direction:row; align-items:center; justify-content:center; margin-top:5rem; ">
            <form  method="POST" style="border: 1px solid #000; padding:2rem; border-radius :7px;">
                {% csrf_token %}
                    <div class="input1" style="display: flex; flex-direction:column ; width: 300px;;">

                        <label  >Admin Name </label>
                        <input type="text" name="an" id="an" >
                    </div>
                    <div class="input1" style="display: flex; flex-direction:column ; width: 300px;; margin-top:1rem;">
                        <label >Password</label>
                        <input type="password" name="pw" id="pw" >
                    </div>
                    
                    <input type="submit" value="Login" class=" btn btn-primary" style="margin-top: 1rem;">
            </form>
        </div>
    </div>


{% endblock %}

templates/about.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>index</title>
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 50px">

<h2 class="text-center">About</h2>
<br><br><br><br>
<div class="row">
<div class="col-sm-4 text-center">
    <img src="{% static 'images/image1.png' %}" alt="No image">

</div>

<div class="col-sm-8 font-weight-bold mt-5">
    Hello Friends .... <br>
    This is a simple hospital management project developed by
    Kanth and using HTML,CSS,Javascripy,bootstrap,Python Django and Sqlite.
</div>
</div>
</div>

{% endblock %}

templates/add_appointment.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>Add Appointment</title>
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 50px">
    <h2 class="text-center">Add Appointment</h2>

    <form action="" method="POST">
        {% csrf_token %}
            <label  >Doctor Name</label>
            <select name="doctor" id="" class="form-control" >
                {% for i in do %}
                    <option value="{{ i.name }}">[{{ i.id }}]  {{ i.name }} </option>
                {% endfor %}
            </select><br><br>

            <label  >Patient Name</label>
            <select name="patient" id="" class="form-control" >
                {% for i in pa %}
                    <option value="{{ i.pname }}">[{{ i.id }}]  {{ i.pname }}</option>
                {% endfor %}
            </select><br><br>
            <label for="">Date</label>
            <input type="date" name="date" id="" class="form-control"  required><br><br>
            <label >Time</label>
            <input type="time" name="time" id="ad" class="form-control"  required><br><br>

            <input type="submit" value="Submit" class="form-control btn btn-primary">
    </form>
</div>

{% if error == "no" %}
<script>
    alert('Record Saved Successfully')
    window.location=('{% url "view_appointment" %}')

</script>
{% elif error == "yes" %}
<script>
    alert('Something went wrong, try again')
</script>
{% endif %}
{% endblock %}

templates/add_doctor.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>Add Doctor</title>
{% endblock %}

{% block body %}

<div class="container"> 
    <br>
    {% if messages %}
        {% for messages in messages %}
            <div class=" alert alert-info alert-dismissable fade show " role="alert">
                {{ messages }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="container" style="margin-top: 50px">
    <h2 class="text-center">Create Doctor</h2>

    <form action="" method="POST">
        {% csrf_token %}
            <label  >Doctor Name</label>
            <input type="text" name="an" id="an" class="form-control" required><br><br>

            <label >Contact</label>
            <input type="text" name="co" id="co" class="form-control" required><br><br>

            <label >Gender</label>
            <input type="radio" name="g" id="g" value="Male" required>Male
            <input type="radio" name="g" value="Female">Female<br><br>

            <label >Specialization</label>
            <input type="text" name="sc" id="sc" class="form-control"  required><br><br>

            <input type="submit" value="Submit" class="form-control btn btn-primary">
    </form>
</div>

{% if error == "no" %}
<script>
    alert('Record Saved Successfully')
    window.location=('{% url "view_doctor" %}')

</script>
{% elif error == "yes" %}
<script>
    alert('Something went wrong, try again')
</script>

{% endif %}
{% endblock %}

templates/add_patient.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>Add Patient</title>
{% endblock %}

{% block body %}
<div class="container"> 
    <br>
    {% if messages %}
        {% for messages in messages %}
            <div class=" alert alert-info alert-dismissable fade show " role="alert">
                {{ messages }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="container" style="margin-top: 50px">
    <h2 class="text-center">Add Patient</h2>

    <form action="" method="POST">
        {% csrf_token %}
        <label for="pname">Pname:</label>
        {{ pfo.pname }}
        <br><br>
    
        <!-- Render Gender with inline radio buttons -->
        <label for="gender">Gender:</label>
        <div>
            {% for radio in pfo.gender %}
                <div style="display: inline-block; margin-right: 10px;">
                    {{ radio.tag }} {{ radio.choice_label }}
                </div>
            {% endfor %}
        </div>
        <br><br>
    
        <!-- Render Pmobile -->
        <label for="pmobile">Pmobile:</label>
        {{ pfo.pmobile }}
        <br><br>
    
        <!-- Render Address -->
        <label for="address">Address:</label>
        {{ pfo.address }}
        <br><br>
    
        <!-- Render Fees -->
        <label for="fees">Fees:</label>
        {{ pfo.fees }}
        <br><br>
    
        <!-- Render Paid -->
        <label for="paid">Paid:</label>
        {{ pfo.paid }}
        <br><br>
    
        <!-- Render Balance -->
        <label for="balance">Balance:</label>
        {{ pfo.balance }}
        <br><br>
    
        <!-- Render Pay -->
        <label for="pay">Pay:</label>
        {{ pfo.pay }}
        <br><br>
    
        <!-- Render Discharge -->
        <label for="discharge">Discharge:</label>
        {{ pfo.discharge }}
        <br><br>
            <input type="submit" value="Submit" class="form-control btn btn-primary">
    </form>
</div>

{% if error == "no" %}
<script>
    alert('Record Saved Successfully')
    window.location=('{% url "view_patient" %}')

</script>
{% elif error == "yes" %}
<script>
    alert('Something went wrong, try again')
</script>
{% endif %}
{% endblock %}

templates/contact.html
{% extends 'dummy.html' %}

{% block title %}
<title>Contact</title>
{% endblock %}

{% block body %}

<div class="container" style="margin-top: 50px ;">
    <h2 class="text-center">CONTACT US </h2>

    <div class="row mt-5 text-center">

        <div class="col-lg-3 col-sm-6 mydivstyle">
            <div class="div1">
                <h4 ><span class="material-symbols-outlined">
                    call
                </span>Contact</h4>
                <p class="mt-3 font-weight-bold"><a class="text-danger" href="tel:+91 1234567890">+91 1234567890</a></p>
            </div>
        </div>

        <div class="col-lg-3 col-sm-6 mydivstyle">
            <div class="div1">
                <h4 ><span class="material-symbols-outlined">
                    mail
                    </span>Mail Id</h4>
                <p class="mt-3 font-weight-bold"><a class="text-danger" href="mailto:gurukanth121@gmail.com">gurukanth121@gmail.com</a></p>
            </div>
        </div>

        <div class="col-lg-3 col-sm-6 mydivstyle">
            <div class="div1">
                <h4 ><span class="material-symbols-outlined">
                    info
                    </span>Office Address</h4>
                <p class="mt-3 font-weight-bold"><a class="text-danger" href="http://maps.google.com/maps?q=Proddatur">Proddatur</a></p>
            </div>
        </div>

        <div class="col-lg-3 col-sm-6 mydivstyle">
            <div class="div1">
                <h4 ><span class="material-symbols-outlined">
                    timer
                    </span>Office Timings</h4>
                <p class="mt-3 font-weight-bold text-danger">9:00 AM to 7:00 PM</p>
            </div>

        </div>
        
    </div>


</div>



{% endblock %}

templates/dummy.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--bootstrap cdn link-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integr84-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!--fontawesom link from w3schools-->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--local staic file link-->
    <link rel="stylesheet" href="{% static 'css/css1.css' %}">
    
    <!--Data table cdn start-->
    
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.0.2/css/buttons.dataTables.css">

    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>

    
    <script>
      $(document).ready(function(){
        $('#example').DataTable( {
          dom:'Bfrtip',
          buttons:[
          'copyHtml5',
          'excelHtml5',
          'csvHtml5',
          'pdfHtml5',
          ]
        });
      });
    </script>

    <!--data tabel end-->

    {% block title %} 
    <title>Document</title>
    {% endblock %} 
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" class="nav-link">HOSPITAL</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              {% if not request.user.is_staff %}
              <li class="nav-item">
                <span class="material-symbols-outlined">
                  home
                  </span>
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <span class="material-symbols-outlined">
                  info
                  </span>
                <a class="nav-link" href="{% url 'about' %}">About</i></a>
              </li>
              <li class="nav-item">
                <span class="material-symbols-outlined">
                  call
                </span>
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
              </li>
              <li class="nav-item">
                <span class="material-symbols-outlined">
                  call
                </span>
                <a class="nav-link" href="{% url 'admin:index' %}">DataBase</a>
              </li>

              {% elif request.user.is_staff %} 

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}"><i class="fa-solid fa-house">Home</i></a>
              </li>

              <li class="nav-item drpdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" >Doctor</a>

                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'add_doctor' %}" >Add Doctor</a>
                  <a class="dropdown-item" href="{% url 'view_doctor' %}" >View Doctor</a>

                </div>
              </li>

              <li class="nav-item drpdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" >Patient</a>

                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'add_patient' %}" >Add Patient</a>
                  <a class="dropdown-item" href="{% url 'view_patient' %}" >View Patient</a>

                </div>
              </li>

              <li class="nav-item drpdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" >Appointment</a>

                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'add_appointment' %}" >Add Appointment</a>
                  <a class="dropdown-item" href="{% url 'view_appointment' %}" >View Appointment</a>

                </div>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'Logout' %}" >Logout</a>
              </li>
              {% endif %} 
            </ul>
          </div>
        </div>
      </nav>





    
    
{% block body %}

{% endblock %} 
</body>
</html>

templates/index.html
{% extends 'dummy.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/css2.css' %}">
{% block title %}
<title>index</title>
{% endblock %}

{% block body %}


    <h2 class="text-center">Admin Dashboard</h2>

    <br><br><br>

    <div class="row">
        <div class="col-sm-4 text-center  mydivstyle"  >
            <div class="div1">
                <h2 style="color: blue">{{ d }}</h2>
                <a href="{% url 'view_doctor' %}"><h4 style="color: red">Doctors</h4>
                </a>
            </div>
        </div>

        <div class="col-sm-4 text-center mydivstyle ">
            <div class="div1">
                <h2 style="color: blue">{{ p }}</h2>
                <a href="{% url 'view_patient' %}"><h4 style="color: red">Patients</h4></a>
            </div>
        </div>

        <div class="col-sm-4 text-center mydivstyle">
            <div class="div1">
                <h2 style="color: blue">{{ a }}</h2>
                <a href="{% url 'view_appointment' %}"><h4 style="color: red">Appointments</h4></a>
            </div>
        </div>
    </div>

{% endblock %}

templates/patient_detail.html
{% extends 'dummy.html' %}

{% block title %}
<title>Contact</title>
{% endblock %}

{% block body %}


    <h1>Patient Details</h1>
    <h2>{{ pat.pname }}</h2>

    
        <p>
            <label for="id_name">Name: </label>
            {{ pat.pname }}
        </p>
        <p>
            <label for="id_gender">Gender: </label>
            {{ pat.gender }}
        </p>
        <p>
            <label for="id_mobile">Mobile: </label>
            {{ pat.pmobile }}
        </p>
        <p>
            <label for="id_address">Address: </label>
            {{ pat.address }}
        </p>
        <p>
            <label for="id_fees">Fees: </label>
            {{ pat.fees }}
        </p>
        <p>
            <label for="id_paid">Paid: </label>
            {{ pat.paid }}
        </p>
        <p>
            <label for="id_balance">Balance: </label>
            {{ pat.balance }}
        </p>
        <form method="post">
            {% csrf_token %}
        <p>
            <label for="pay">Pay: </label>
            <input type="number" name="pay" id="pay">
        </p>
        <button type="submit" class="btn btn-primary">PAY</button>
        </form>

    <a href="{% url 'view_patient' %}">Back to Patient List</a>

    {% endblock %}

templates/view_appointment.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>View Appointment</title>
{% endblock %}

{% block body %}
<div class="container" style="margin-top:50px">
    <h2 class="text-center">View Patient</h2>
    <br><br>

    <table class="table table-hover" id="example">
        <thead>
            <tr class="table-row">
                <th  >Doctor Name</th>
                <th>Patient Name</th>
                
                <th> Date</th>
                <th> Time</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for i in appo %}
                <tr>
                    <td>{{ i.doctor }}</td>
                    <td>{{ i.patient }}</td>
                   
                    <td>{{ i.date}}</td>
                    <td>{{ i.time }}</td>
                    <td><a href="{% url 'delete_appointment' i.id %}" onclick="return confirm('Are u really want to delete')" class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% endblock %}

templates/view_doctor.html
{% extends 'dummy.html' %}
{% load static %}
{% block title %}
<title>View Doctor</title>
{% endblock %}

{% block body %}
<div class="container" style="margin-top:50px">
    <h2 class="text-center">View Doctor</h2>
    <br><br>

    <table class="table table-hover" id="example">
        <thead>
            <tr class="table-row">
                <th  >Doctor ID</th>
                <th>Doctor Name</th>
                <th>Gender</th>
                <th> Contact</th>
                <th> Specialization</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for i in doc %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.gender }}</td>
                    <td>{{ i.mobile }}</td>
                    <td>{{ i.specialization }}</td>
                    <td><a href="{% url 'delete_doctor' i.id %}" onclick="return confirm('Are u really want to delete')" class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>



{% endblock %}